repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff-format
      - id: ruff
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv lock --check
        entry: uv lock --check
        language: system
        pass_filenames: false
      - id: fmt-sh
        name: scripts/dev/fmt.sh
        entry: scripts/dev/fmt.sh
        language: system
        pass_filenames: false
      - id: dep-sync-py
        name: scripts/dev/dep_sync_py.sh
        entry: scripts/dev/dep_sync_py.sh
        language: system
        pass_filenames: false
      - id: test-py
        name: scripts/dev/test_py.sh
        entry: scripts/dev/test_py.sh
        language: system
        pass_filenames: false
        stages: [push]
      - id: supply-guard
        name: supply-guard
        entry: bash scripts/dev/supply_guard.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
