ci:
  autofix_prs: true
  autofix_commit_message: "chore: pre-commit.ci auto fixes"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: security-autofix
        name: security autofix (Bandit allowlist)
        entry: python scripts/security_autofix.py --check
        language: system
        pass_filenames: false
        stages: [manual]
