ci:
  autofix_prs: true
  autofix_commit_message: "chore: pre-commit.ci auto fixes"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff-format
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
  - repo: local
    hooks:
      - id: legacy-import-ban
        name: legacy orchestrator import ban
        entry: bash -c "rg -n \"app\\.orchestrator\\.download_flow\" --glob '!docs/archive/**' --glob '!CHANGELOG*' && exit 1 || exit 0"
        language: system
        pass_filenames: false
