services:
  harmony:
    image: ghcr.io/bozzfozz/harmony:latest
    container_name: harmony
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql+psycopg://harmony:harmony@postgres:5432/harmony
      HARMONY_API_KEYS: change-me
      ALLOWED_ORIGINS: http://localhost:8080
      PUBLIC_BACKEND_URL: http://localhost:8080
      PUBLIC_SENTRY_DSN: ""
      PUBLIC_FEATURE_FLAGS: "{}"
    ports:
      - "8080:8080"
    volumes:
      - harmony-data:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: harmony
      POSTGRES_USER: harmony
      POSTGRES_PASSWORD: harmony
    ports:
      - "5432:5432"
    volumes:
      - harmony-pg-data:/var/lib/postgresql/data

volumes:
  harmony-data:
  harmony-pg-data:
