services:
  harmony:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      DATABASE_URL: postgresql+psycopg://harmony:harmony@postgres:5432/harmony
      HARMONY_LOG_LEVEL: DEBUG
      HARMONY_API_KEYS: dev-key
      ALLOWED_ORIGINS: http://localhost:8080
      PUBLIC_BACKEND_URL: http://localhost:8080
      PUBLIC_SENTRY_DSN: ""
      PUBLIC_FEATURE_FLAGS: "{}"
    volumes:
      - ./app:/app/app
