services:
  harmony:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      UMASK: "${UMASK:-007}"
      OAUTH_SPLIT_MODE: "${OAUTH_SPLIT_MODE:-false}"
      OAUTH_STATE_DIR: /data/runtime/oauth_state
      OAUTH_STATE_TTL_SEC: "${OAUTH_STATE_TTL_SEC:-600}"
      OAUTH_STORE_HASH_CV: "${OAUTH_STORE_HASH_CV:-true}"
      DATABASE_URL: sqlite+aiosqlite:///data/harmony.db
      DOWNLOADS_DIR: /data/downloads
      MUSIC_DIR: /data/music
      WORKER_CONCURRENCY: "${WORKER_CONCURRENCY:-4}"
      MAX_RETRIES: "${DOWNLOAD_MAX_RETRIES:-5}"
      SLSKD_BASE_URL: "${SLSKD_BASE_URL:-http://localhost:5030}"
      HARMONY_LOG_LEVEL: DEBUG
      HARMONY_API_KEYS: "${HARMONY_API_KEYS:-dev-key}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS:-http://localhost:8080}"
      PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL:-http://localhost:8080}"
      PUBLIC_SENTRY_DSN: "${PUBLIC_SENTRY_DSN:-}"
      PUBLIC_FEATURE_FLAGS: "${PUBLIC_FEATURE_FLAGS:-{}}"
      DB_RESET: "${DB_RESET:-0}"
    ports:
      - "8080:8080"
    volumes:
      - harmony-data:/data
      - ./app:/app/app
      - type: bind
        source: /srv/media/downloads
        target: /data/downloads
      - type: bind
        source: /srv/media/music
        target: /data/music
      - type: bind
        source: /srv/harmony/runtime/oauth_state
        target: /data/runtime/oauth_state

volumes:
  harmony-data:
    driver: local
