services:
  harmony:
    image: ghcr.io/bozzfozz/harmony:1.0.0
    container_name: harmony
    environment:
      TZ: Etc/UTC
      PUID: "1000"
      PGID: "1000"
      # Add `HARMONY_API_KEYS` via an `.env` file or here before exposing Harmony to
      # untrusted networks. The default stack keeps authentication disabled for
      # local deployments.
    volumes:
      - /mnt/harmony:/data
      - /mnt/data/downloads:/downloads
      - /mnt/data/music:/music
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/health/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
