services:
  harmony:
    image: ghcr.io/bozzfozz/harmony:latest
    container_name: harmony
    environment:
      TZ: Etc/UTC
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /mnt/harmony:/data
      - /mnt/data/downloads:/data/downloads
      - /mnt/data/music:/data/music
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/health/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
