services:
  harmony:
    image: ghcr.io/bozzfozz/harmony:latest
    container_name: harmony
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: sqlite:////data/harmony.db
      HARMONY_API_KEYS: change-me
      ALLOWED_ORIGINS: http://localhost:8080
      PUBLIC_BACKEND_URL: http://localhost:8080
      PUBLIC_SENTRY_DSN: ""
      PUBLIC_FEATURE_FLAGS: "{}"
    ports:
      - "8080:8080"
    volumes:
      - harmony-data:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  harmony-data:
