version: "3.9"

services:
  harmony:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: "${PUID:-1000}:${PGID:-1000}"
    ports:
      - "8080:8080"
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/music:/music
