version: "3.9"

services:
  backend:
    build: .
    container_name: harmony-backend
    environment:
      - DATABASE_URL=sqlite:///./harmony.db
      - HARMONY_LOG_LEVEL=INFO
      - HARMONY_API_KEYS=dev-key
      - ALLOWED_ORIGINS=http://localhost:8000
      - PUBLIC_BACKEND_URL=http://localhost:8000
      - PUBLIC_SENTRY_DSN=
      - PUBLIC_FEATURE_FLAGS={}
    ports:
      - "8000:8000"
