version: "3.8"

services:
  harmony:
    image: ghcr.io/bozzfozz/harmony:latest
    container_name: harmony
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./music:/music
    restart: unless-stopped
