[tool.ruff]
line-length = 100
src = ["app", "tests"]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["app", "tests"]
combine-as-imports = true
force-sort-within-sections = true
case-sensitive = false
split-on-trailing-comma = true
lines-between-types = 1

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
fail_under = 0
show_missing = true
skip_covered = false

