[tool.black]
line-length = 100
target-version = ["py311"]
include = "\\.pyi?$"
exclude = '''
/(
    \\.git
    | \\.mypy_cache
    | \\.ruff_cache
    | build
    | dist
    | archive
    | frontend/node_modules
)/
'''

[tool.ruff]
line-length = 100
src = ["app", "tests"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["app", "tests"]
combine-as-imports = true
force-sort-within-sections = true
split-on-trailing-comma = true

[tool.isort]
profile = "black"
known_first_party = ["app", "tests"]

