[tool.black]
line-length = 88
target-version = ["py311"]
include = "\\.pyi?$"
exclude = '''
/(
    \\.git
    | \\.mypy_cache
    | \\.ruff_cache
    | build
    | dist
    | archive
    | frontend/node_modules
)/
'''

[tool.ruff]
line-length = 88
src = ["app", "tests"]
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

