[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "TESTS", "FIRSTPARTY", "LOCALFOLDER"]
known_tests = ["tests"]
known_first_party = ["app"]
no_lines_before = ["TESTS"]

[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
fail_under = 0
show_missing = true
skip_covered = false

[tool.harmony.coverage]
compare_branch = "origin/main"
diff_fail_under = 85
report_fail_under = 0
