# .github/workflows/auto-merge-codex.yml
# PRs, deren Quell-Branch mit "codex/" beginnt, automatisch mergen
# und anschließend den Branch löschen – ganz ohne Labels.

name: Auto-merge codex/* PRs & delete branch

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable auto-merge (squash) for codex/*
    if: >
      github.event.action != 'closed' &&
      startsWith(github.event.pull_request.head.ref, 'codex/') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable native auto-merge (squash + delete branch)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          # Aktiviert GitHubs Auto-Merge. Der Merge wird automatisch ausgeführt,
          # sobald alle Schutzregeln (Checks/Reviews) erfüllt sind.
          gh pr merge --auto --squash --delete-branch "$PR_URL"

  delete-head-branch:
    name: Delete merged head branch (fallback)
    if: >
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'codex/') &&
      github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch if not already removed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          set -e
          if [ "$BRANCH" = "$DEFAULT_BRANCH" ]; then
            echo "Skip deleting default branch: $DEFAULT_BRANCH"
            exit 0
          fi
          # Löscht refs/heads/<branch>; ignoriert Fehler (z. B. bereits gelöscht/geschützt)
          gh api -X DELETE "repos/$OWNER/$REPO/git/refs/heads/$BRANCH" || true

concurrency:
  group: auto-merge-codex-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false
