name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-frontend:
    name: detect-frontend
    runs-on: ubuntu-latest
    outputs:
      has_frontend: ${{ steps.check.outputs.has_frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect frontend workspace
        id: check
        run: |
          if [ -f frontend/package.json ]; then
            echo "has_frontend=true" >>"$GITHUB_OUTPUT"
          else
            echo "has_frontend=false" >>"$GITHUB_OUTPUT"
          fi

  ci-backend:
    name: ci-backend
    runs-on: ubuntu-latest
    env:
      RUN_POSTGRES_TESTS: "0"
      PYTHON_VERSION: "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml

      - name: Install backend tooling
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install \
            isort \
            mypy \
            pytest-cov

      - name: Mypy (static typing)
        run: mypy app

      - name: Isort (imports)
        run: isort --check-only .

      - name: Pytest (unit + coverage)
        env:
          PYTEST_ADDOPTS: "-m 'not postgres'"
        run: |
          mkdir -p reports
          pytest \
            --junitxml=reports/junit.xml \
            --cov=app \
            --cov-report=xml:reports/coverage.xml \
            --cov-report=term \
            --cov-fail-under=85

      - name: pip-audit (dependencies)
        run: pip-audit -r requirements.txt

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: reports/coverage.xml
          retention-days: 7

      - name: Upload junit artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-tests
          path: reports/junit.xml
          retention-days: 7

  ci-frontend:
    name: ci-frontend
    runs-on: ubuntu-latest
    needs:
      - detect-frontend
      - ci-backend
    if: ${{ needs.detect-frontend.outputs.has_frontend == 'true' }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci --no-audit --no-fund

      - name: ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --runInBand
