name: CI

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
      - chore/**
      - ci/**
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install black==24.8.0 ruff==0.12.11 mypy
      - name: Wiring audit
        run: python scripts/audit_wiring.py
      - name: Ruff (lint + import order)
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Mypy
        run: mypy app
      - name: Pytest
        run: pytest -q
      - name: pip-audit (advisories only)
        run: pip-audit -r requirements.txt || true
      - name: Radon
        run: radon cc -s -a app
      - name: Vulture
        run: vulture app tests --exclude .venv

  backend-postgres:
    runs-on: ubuntu-latest
    needs: backend
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: harmony
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/harmony
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install black==24.8.0 ruff==0.12.11 mypy
      - name: Wait for database
        run: |
          for attempt in {1..30}; do
            if pg_isready --host=localhost --port=5432 --username=postgres; then
              exit 0
            fi
            sleep 1
          done
          exit 1
      - name: Migration round trip
        run: |
          alembic upgrade head
          alembic downgrade base
          alembic upgrade head
      - name: Pytest (PostgreSQL smoke)
        run: |
          pytest tests/migrations/test_upgrade_downgrade_postgres.py -q
          pytest tests/test_artists.py -q
          pytest tests/workers/test_watchlist_worker.py::test_watchlist_handler_success_enqueues_sync_job -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Test
        working-directory: frontend
        run: npm test --silent
      - name: Typecheck
        working-directory: frontend
        run: npm run typecheck
      - name: Build
        working-directory: frontend
        run: npm run build

  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate OpenAPI snapshot
        run: |
          python - <<'PY'
          import json
          from pathlib import Path

          from app.main import app

          snapshot_path = Path('tests/snapshots/openapi.json')
          current_schema = app.openapi()
          snapshot_schema = json.loads(snapshot_path.read_text())
          if current_schema != snapshot_schema:
              raise SystemExit('OpenAPI schema drift detected. Update tests/snapshots/openapi.json')
          PY

  security-bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-bandit-${{ hashFiles('requirements-dev.txt', '.bandit') }}
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit==1.7.9
      - name: Security scan (Bandit)
        run: bandit -c .bandit -r app
