name: docker-image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Docker assets
        run: |
          test -f docker/Dockerfile || (echo "::error::docker/Dockerfile fehlt"; exit 1)
          head -n 1 docker/services.d/harmony/run | grep -q "/command/with-contenv" || (echo "::error::Shebang in services.d/harmony/run falsch"; exit 1)
          head -n 1 docker/cont-init.d/10-prepare-dirs | grep -q "/command/with-contenv" || (echo "::error::Shebang in cont-init.d/10-prepare-dirs falsch"; exit 1)

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/harmony:latest
            ghcr.io/${{ github.repository_owner }}/harmony:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=harmony
            org.opencontainers.image.version=latest
