name: release-check

on:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'release/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    name: release-check (Python 3.11)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Guard against requirements*.txt files
        run: |
          set -euo pipefail
          if ls requirements*.txt 1>/dev/null 2>&1; then
            echo "requirements*.txt files detected; please rely on uv instead." >&2
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.7.0"

      - name: Pin Python for uv
        run: uv python pin 3.11

      - name: Show uv version
        run: uv --version

      - name: Prune uv cache
        run: uv cache prune

      - name: Check lockfile freshness
        run: uv lock --check

      - name: Install dependencies
        run: |
          uv sync --frozen --project . --group dev --group test

      - name: Run make release-check
        env:
          SLSKD_API_KEY: release-check-ci
          HARMONY_API_KEYS: ui-smoke-key
          RELEASE_CHECK_COMMANDS: |
            make fmt
            make lint
            make dep-sync
            make supply-guard
            make smoke
            make docs-verify
            make pip-audit
            make ui-smoke
        run: |
          set -euo pipefail
          mkdir -p reports/release-check
          uv run --no-sync --group dev --group test make release-check |& tee reports/release-check/release-check.log
          git diff --exit-code

      - name: Verify packaging pipeline
        run: |
          set -euo pipefail
          uv run --no-sync --group dev --group test make package-verify

      - name: Upload packaging artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: release-packaging-artifacts
          path: dist/
          if-no-files-found: warn

      - name: Upload release-check logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: release-check-logs
          path: reports/release-check/
          if-no-files-found: warn
