name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    name: build-and-release
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build backend distribution
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Archive backend distribution
        run: |
          ls dist

      - name: Set up Node.js
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org

      - name: Remove existing node_modules
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: rm -rf node_modules

      - name: Configure deterministic npm install
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          set -euo pipefail
          tmp_cache="$(mktemp -d)"
          echo "Using ephemeral npm cache at $tmp_cache"
          echo "NPM_CONFIG_CACHE=$tmp_cache" >> "$GITHUB_ENV"
          export NPM_CONFIG_CACHE="$tmp_cache"
          npm config set cache "$tmp_cache"
          npm config set prefer-online true
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-timeout 600000
          npm config set registry https://registry.npmjs.org/

      - name: Install frontend dependencies
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          set -euo pipefail
          attempts=0
          max_attempts=3
          until [ "$attempts" -ge "$max_attempts" ]; do
            attempts=$((attempts + 1))
            echo "npm ci attempt ${attempts}/${max_attempts}"
            if npm ci --no-audit --no-fund; then
              echo "npm ci completed successfully on attempt ${attempts}."
              break
            fi
            if [ "$attempts" -ge "$max_attempts" ]; then
              echo "::error::npm ci failed after ${max_attempts} attempts."
              exit 1
            fi
            echo "npm ci failed (attempt ${attempts}); cleaning cache and retrying..."
            npm cache clean --force
            sleep 5
          done

      - name: Build frontend bundle
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          npm run build
          tar -C dist -czf ../frontend-dist.tar.gz .

      - name: Collect release assets
        id: assets
        run: |
          set -euo pipefail
          files=$(printf "%s\n" dist/*)
          if [ -f frontend-dist.tar.gz ]; then
            files="$files\nfrontend-dist.tar.gz"
          fi
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          printf "%s\n" $files >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.assets.outputs.files }}
          generate_release_notes: true
