name: uv-lock-guard

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check-lock:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.7.0"

      - name: Verify uv lockfile is up to date
        run: uv lock --check
